services:
  nginx:
    image: nginx:latest
    container_name: gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - frontend-service

  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  auth-service:
    build: ./auth
    container_name: auth-service
    restart: always
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/ # Todo: use .env
    depends_on:
      - mongo
    volumes:
      - ./auth:/app

  frontend-service:
    build: ./frontend
    container_name: frontend-service
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

volumes:
  mongo-data:
