services:
  nginx:
    image: nginx:latest
    container_name: gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - frontend-service

  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  auth-service:
    build: 
      context: ./auth
      args:
        NODE_ENV: development
    container_name: auth-service
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./auth:/app
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=development

  auth-service-prod:
    build: 
      context: ./auth
      args:
        NODE_ENV: production
    container_name: auth-service-prod
    restart: always
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://root:example@mongo:27017/

  frontend-service:
    build: ./frontend
    container_name: frontend-service
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

volumes:
  mongo-data:
